language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t ahmedaminesoltani/docker-react -f Dockerfile.dev .

script:
  - docker container run -e CI=true  ahmedaminesoltani/docker-react npm run test 
# -e CI=true used to leave the interactive test mode while running npm run test watch video number 94


