#language: node_js 
sudo: required
services:
  - docker

before_install:
  - docker build -t ahmedaminesoltani/docker-react -f Dockerfile.dev .

script:
  - docker container run -e CI=true  ahmedaminesoltani/docker-react npm run test 
# -e CI=true used to leave the interactive test mode while running npm run test watch video number 94


deploy:
  edge: true
  provider: elasticbeanstalk 
  region: "eu-west-3"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-771253377026"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  